# Generated by Django 5.0.7 on 2024-07-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('sapo', models.CharField(max_length=255)),
                ('date_create', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
